name: cf.yaml

on:
  workflow_dispatch:

jobs:
  shell:
    runs-on: ubuntu-latest
    name: Test a cf tunnel
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Start ssh server
      uses: r-hub/actions/ssh-server@main
